<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPpchych\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPpchych/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPpchych.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerPpchych\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerPpchych\appProdProjectContainer([
    'container.build_hash' => 'Ppchych',
    'container.build_id' => 'ede514aa',
    'container.build_time' => 1585677708,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPpchych');
